### ISSUE TITLE
Argument must be of type ramazancetinkaya\PDO, PDO given

### ISSUE THREAD

**Issue by openstudio-one** [ramazancetinkaya/mysql-backup#11]
Sorry, I am already back with another issue!

`Fatal error: Uncaught TypeError: ramazancetinkaya\BackupLibrary::__construct(): Argument #1 ($pdo) must be of type ramazancetinkaya\PDO, PDO given, called in mysql_backup.php on line 23 and defined in /library/mysql_backup/vendor/ramazancetinkaya/mysql-backup/src/BackupLibrary.php:37 Stack trace: #0 mysql_backup.php(23): ramazancetinkaya\BackupLibrary->__construct(Object(PDO)) #1 {main} thrown in /library/mysql_backup/vendor/ramazancetinkaya/mysql-backup/src/BackupLibrary.php on line 37`

**Comment by ramazancetinkaya** [comment]
Can you try again?

**Comment by ramazancetinkaya** [comment]
@openstudio-one 

I have solved the problem. I am updating the relevant files.

**Comment by ramazancetinkaya** [comment]
Hello, @openstudio-one

The tests I conducted show that the library is functioning properly. To learn how to use the class, please don't forget to review the README.md page.

Have a great day!

**Comment by ramazancetinkaya** [comment]
Then don't forget to give a star to the repository⭐😄 

I hope you have a wonderful day.
